# Generated by Django 4.2.2 on 2023-11-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_userprofile_delete_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
